/* generated by gulpfile.js */
/*eslint camelcase: 0 */
import _values from '../collectors/_values';
import count from '../collectors/count';
import filteredCount from '../collectors/filteredCount';
import max from '../collectors/max';
import mean from '../collectors/mean';
import min from '../collectors/min';
import powerSumAvg_running from '../collectors/powerSumAvg_running';
import standardDeviation_running from '../collectors/standardDeviation_running';
import standardDeviation_stable from '../collectors/standardDeviation_stable';
import sum from '../collectors/sum';
import sumOfSquaredDeviations_stable from '../collectors/sumOfSquaredDeviations_stable';
import variance_running from '../collectors/variance_running';
import variance_stable from '../collectors/variance_stable';
export {
  _values,
  count,
  filteredCount,
  max,
  mean,
  min,
  powerSumAvg_running,
  standardDeviation_running,
  standardDeviation_stable,
  sum,
  sumOfSquaredDeviations_stable,
  variance_running,
  variance_stable
};
