/* generated by gulpfile.js */
/*eslint camelcase: 0 */
import Count from '../collectors/number/Count';
import FilteredCount from '../collectors/number/FilteredCount';
import Max from '../collectors/number/Max';
import Mean from '../collectors/number/Mean';
import Min from '../collectors/number/Min';
import PowerSumAvgRunning from '../collectors/number/PowerSumAvgRunning';
import StandardDeviationRunning from '../collectors/number/StandardDeviationRunning';
import StandardDeviationStable from '../collectors/number/StandardDeviationStable';
import Sum from '../collectors/number/Sum';
import SumOfSquaredDeviationsStable from '../collectors/number/SumOfSquaredDeviationsStable';
import Values from '../collectors/number/Values';
import VarianceRunning from '../collectors/number/VarianceRunning';
import VarianceStable from '../collectors/number/VarianceStable';
export {
  Count,
  FilteredCount,
  Max,
  Mean,
  Min,
  PowerSumAvgRunning,
  StandardDeviationRunning,
  StandardDeviationStable,
  Sum,
  SumOfSquaredDeviationsStable,
  Values,
  VarianceRunning,
  VarianceStable
};
