/* generated by gulpfile.js */
/*eslint camelcase: 0 */
import even from '../filters/even';
import float from '../filters/float';
import integer from '../filters/integer';
import negative from '../filters/negative';
import nonZero from '../filters/nonZero';
import odd from '../filters/odd';
import positive from '../filters/positive';
import prime from '../filters/prime';
import zero from '../filters/zero';
export {
  even,
  float,
  integer,
  negative,
  nonZero,
  odd,
  positive,
  prime,
  zero
};
