window.esdocSearchIndex = [
  [
    &quot;stats-collector/lib/stats/number/advancednumberstats~advancednumberstats&quot;,
    &quot;class/src/stats/number/AdvancedNumberStats.js~AdvancedNumberStats.html&quot;,
    &quot;<span>AdvancedNumberStats</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/stats/number/AdvancedNumberStats</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/number/arithmeticmean~arithmeticmean&quot;,
    &quot;class/src/collectors/number/ArithmeticMean.js~ArithmeticMean.html&quot;,
    &quot;<span>ArithmeticMean</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/number/ArithmeticMean</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/stats/basestats~basestats&quot;,
    &quot;class/src/stats/BaseStats.js~BaseStats.html&quot;,
    &quot;<span>BaseStats</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/stats/BaseStats</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/stats/number/basicnumberstats~basicnumberstats&quot;,
    &quot;class/src/stats/number/BasicNumberStats.js~BasicNumberStats.html&quot;,
    &quot;<span>BasicNumberStats</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/stats/number/BasicNumberStats</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/collector~collector&quot;,
    &quot;class/src/collectors/Collector.js~Collector.html&quot;,
    &quot;<span>Collector</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/Collector</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/number/count~count&quot;,
    &quot;class/src/collectors/number/Count.js~Count.html&quot;,
    &quot;<span>Count</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/number/Count</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/number/filteredcount~filteredcount&quot;,
    &quot;class/src/collectors/number/FilteredCount.js~FilteredCount.html&quot;,
    &quot;<span>FilteredCount</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/number/FilteredCount</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/number/geometricmean~geometricmean&quot;,
    &quot;class/src/collectors/number/GeometricMean.js~GeometricMean.html&quot;,
    &quot;<span>GeometricMean</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/number/GeometricMean</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/number/harmonicmean~harmonicmean&quot;,
    &quot;class/src/collectors/number/HarmonicMean.js~HarmonicMean.html&quot;,
    &quot;<span>HarmonicMean</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/number/HarmonicMean</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/number/max~max&quot;,
    &quot;class/src/collectors/number/Max.js~Max.html&quot;,
    &quot;<span>Max</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/number/Max</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/number/mean~mean&quot;,
    &quot;class/src/collectors/number/Mean.js~Mean.html&quot;,
    &quot;<span>Mean</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/number/Mean</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/number/median~median&quot;,
    &quot;class/src/collectors/number/Median.js~Median.html&quot;,
    &quot;<span>Median</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/number/Median</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/number/midrange~midrange&quot;,
    &quot;class/src/collectors/number/MidRange.js~MidRange.html&quot;,
    &quot;<span>MidRange</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/number/MidRange</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/number/min~min&quot;,
    &quot;class/src/collectors/number/Min.js~Min.html&quot;,
    &quot;<span>Min</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/number/Min</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/stats/number/numberstats~numberstats&quot;,
    &quot;class/src/stats/number/NumberStats.js~NumberStats.html&quot;,
    &quot;<span>NumberStats</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/stats/number/NumberStats</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/number/powersumavgrunning~powersumavgrunning&quot;,
    &quot;class/src/collectors/number/PowerSumAvgRunning.js~PowerSumAvgRunning.html&quot;,
    &quot;<span>PowerSumAvgRunning</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/number/PowerSumAvgRunning</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/number/product~product&quot;,
    &quot;class/src/collectors/number/Product.js~Product.html&quot;,
    &quot;<span>Product</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/number/Product</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/number/range~range&quot;,
    &quot;class/src/collectors/number/Range.js~Range.html&quot;,
    &quot;<span>Range</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/number/Range</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/number/standarddeviationrunning~standarddeviationrunning&quot;,
    &quot;class/src/collectors/number/StandardDeviationRunning.js~StandardDeviationRunning.html&quot;,
    &quot;<span>StandardDeviationRunning</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/number/StandardDeviationRunning</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/number/standarddeviationstable~standarddeviationstable&quot;,
    &quot;class/src/collectors/number/StandardDeviationStable.js~StandardDeviationStable.html&quot;,
    &quot;<span>StandardDeviationStable</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/number/StandardDeviationStable</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/number/sum~sum&quot;,
    &quot;class/src/collectors/number/Sum.js~Sum.html&quot;,
    &quot;<span>Sum</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/number/Sum</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/number/sumofrecipricals~sumofrecipricals&quot;,
    &quot;class/src/collectors/number/SumOfRecipricals.js~SumOfRecipricals.html&quot;,
    &quot;<span>SumOfRecipricals</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/number/SumOfRecipricals</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/number/sumofsquareddeviationsstable~sumofsquareddeviationsstable&quot;,
    &quot;class/src/collectors/number/SumOfSquaredDeviationsStable.js~SumOfSquaredDeviationsStable.html&quot;,
    &quot;<span>SumOfSquaredDeviationsStable</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/number/SumOfSquaredDeviationsStable</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/number/values~values&quot;,
    &quot;class/src/collectors/number/Values.js~Values.html&quot;,
    &quot;<span>Values</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/number/Values</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/number/valuessorted~valuessorted&quot;,
    &quot;class/src/collectors/number/ValuesSorted.js~ValuesSorted.html&quot;,
    &quot;<span>ValuesSorted</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/number/ValuesSorted</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/number/variancerunning~variancerunning&quot;,
    &quot;class/src/collectors/number/VarianceRunning.js~VarianceRunning.html&quot;,
    &quot;<span>VarianceRunning</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/number/VarianceRunning</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/number/variancestable~variancestable&quot;,
    &quot;class/src/collectors/number/VarianceStable.js~VarianceStable.html&quot;,
    &quot;<span>VarianceStable</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/number/VarianceStable</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/filters/number/even~even&quot;,
    &quot;function/index.html#static-function-even&quot;,
    &quot;<span>even</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/filters/number/even</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/filters/number/float~float&quot;,
    &quot;function/index.html#static-function-float&quot;,
    &quot;<span>float</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/filters/number/float</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/filters/number/integer~integer&quot;,
    &quot;function/index.html#static-function-integer&quot;,
    &quot;<span>integer</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/filters/number/integer</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/helpers/leastfactor~leastfactor&quot;,
    &quot;function/index.html#static-function-leastFactor&quot;,
    &quot;<span>leastFactor</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/helpers/leastFactor</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/filters/number/negative~negative&quot;,
    &quot;function/index.html#static-function-negative&quot;,
    &quot;<span>negative</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/filters/number/negative</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/filters/number/nonzero~nonzero&quot;,
    &quot;function/index.html#static-function-nonZero&quot;,
    &quot;<span>nonZero</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/filters/number/nonZero</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/filters/number/odd~odd&quot;,
    &quot;function/index.html#static-function-odd&quot;,
    &quot;<span>odd</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/filters/number/odd</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/filters/number/positive~positive&quot;,
    &quot;function/index.html#static-function-positive&quot;,
    &quot;<span>positive</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/filters/number/positive</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/filters/number/prime~prime&quot;,
    &quot;function/index.html#static-function-prime&quot;,
    &quot;<span>prime</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/filters/number/prime</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/filters/number/zero~zero&quot;,
    &quot;function/index.html#static-function-zero&quot;,
    &quot;<span>zero</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/filters/number/zero</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~array&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Array&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~arraybuffer&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~boolean&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Boolean&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~dataview&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~DataView&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~date&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Date&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~error&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Error&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~evalerror&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~EvalError&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~float32array&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Float32Array&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~float64array&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Float64Array&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~function&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Function&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~generator&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Generator&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~generatorfunction&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~infinity&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Infinity&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~int16array&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Int16Array&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~int32array&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Int32Array&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~int8array&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Int8Array&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~internalerror&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~InternalError&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~json&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~JSON&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~map&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Map&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~nan&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~NaN&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~number&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Number&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~object&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Object&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~promise&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Promise&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~proxy&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Proxy&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~rangeerror&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~RangeError&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~referenceerror&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~ReferenceError&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~reflect&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Reflect&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~regexp&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~RegExp&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~set&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Set&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~string&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~String&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~symbol&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Symbol&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~syntaxerror&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~SyntaxError&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~typeerror&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~TypeError&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~urierror&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~URIError&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~uint16array&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Uint16Array&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~uint32array&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Uint32Array&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~uint8array&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Uint8Array&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~uint8clampedarray&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~weakmap&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~WeakMap&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~weakset&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~WeakSet&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~boolean&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~boolean&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~function&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~function&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~null&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~null&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~number&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~number&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~object&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~object&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~string&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~string&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~undefined&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~undefined&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/webapiexternal.js~audiocontext&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/WebAPIExternal.js~AudioContext&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/webapiexternal.js~canvasrenderingcontext2d&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/webapiexternal.js~documentfragment&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/WebAPIExternal.js~DocumentFragment&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/webapiexternal.js~element&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/WebAPIExternal.js~Element&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/webapiexternal.js~event&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/WebAPIExternal.js~Event&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/webapiexternal.js~node&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/WebAPIExternal.js~Node&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/webapiexternal.js~nodelist&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/WebAPIExternal.js~NodeList&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/webapiexternal.js~xmlhttprequest&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/WebAPIExternal.js~XMLHttpRequest&quot;,
    &quot;external&quot;
  ],
  [
    &quot;src/cli.js&quot;,
    &quot;file/src/cli.js.html&quot;,
    &quot;src/cli.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/collector.js&quot;,
    &quot;file/src/collectors/Collector.js.html&quot;,
    &quot;src/collectors/Collector.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/collector.js~collector#constructor&quot;,
    &quot;class/src/collectors/Collector.js~Collector.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/Collector.js~Collector#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/collector.js~collector#initialvalue&quot;,
    &quot;class/src/collectors/Collector.js~Collector.html#instance-member-initialValue&quot;,
    &quot;src/collectors/Collector.js~Collector#initialValue&quot;,
    &quot;member&quot;
  ],
  [
    &quot;src/collectors/collector.js~collector#name&quot;,
    &quot;class/src/collectors/Collector.js~Collector.html#instance-member-name&quot;,
    &quot;src/collectors/Collector.js~Collector#name&quot;,
    &quot;member&quot;
  ],
  [
    &quot;src/collectors/collector.js~collector#requirements&quot;,
    &quot;class/src/collectors/Collector.js~Collector.html#instance-member-requirements&quot;,
    &quot;src/collectors/Collector.js~Collector#requirements&quot;,
    &quot;member&quot;
  ],
  [
    &quot;src/collectors/number/arithmeticmean.js&quot;,
    &quot;file/src/collectors/number/ArithmeticMean.js.html&quot;,
    &quot;src/collectors/number/ArithmeticMean.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/number/arithmeticmean.js~arithmeticmean#constructor&quot;,
    &quot;class/src/collectors/number/ArithmeticMean.js~ArithmeticMean.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/number/ArithmeticMean.js~ArithmeticMean#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/arithmeticmean.js~arithmeticmean#handleget&quot;,
    &quot;class/src/collectors/number/ArithmeticMean.js~ArithmeticMean.html#instance-method-handleGet&quot;,
    &quot;src/collectors/number/ArithmeticMean.js~ArithmeticMean#handleGet&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/count.js&quot;,
    &quot;file/src/collectors/number/Count.js.html&quot;,
    &quot;src/collectors/number/Count.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/number/count.js~count#constructor&quot;,
    &quot;class/src/collectors/number/Count.js~Count.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/number/Count.js~Count#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/count.js~count#handleprocess&quot;,
    &quot;class/src/collectors/number/Count.js~Count.html#instance-method-handleProcess&quot;,
    &quot;src/collectors/number/Count.js~Count#handleProcess&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/filteredcount.js&quot;,
    &quot;file/src/collectors/number/FilteredCount.js.html&quot;,
    &quot;src/collectors/number/FilteredCount.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/number/filteredcount.js~filteredcount#constructor&quot;,
    &quot;class/src/collectors/number/FilteredCount.js~FilteredCount.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/number/FilteredCount.js~FilteredCount#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/filteredcount.js~filteredcount#handleprocess&quot;,
    &quot;class/src/collectors/number/FilteredCount.js~FilteredCount.html#instance-method-handleProcess&quot;,
    &quot;src/collectors/number/FilteredCount.js~FilteredCount#handleProcess&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/geometricmean.js&quot;,
    &quot;file/src/collectors/number/GeometricMean.js.html&quot;,
    &quot;src/collectors/number/GeometricMean.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/number/geometricmean.js~geometricmean#constructor&quot;,
    &quot;class/src/collectors/number/GeometricMean.js~GeometricMean.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/number/GeometricMean.js~GeometricMean#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/geometricmean.js~geometricmean#handleget&quot;,
    &quot;class/src/collectors/number/GeometricMean.js~GeometricMean.html#instance-method-handleGet&quot;,
    &quot;src/collectors/number/GeometricMean.js~GeometricMean#handleGet&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/harmonicmean.js&quot;,
    &quot;file/src/collectors/number/HarmonicMean.js.html&quot;,
    &quot;src/collectors/number/HarmonicMean.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/number/harmonicmean.js~harmonicmean#constructor&quot;,
    &quot;class/src/collectors/number/HarmonicMean.js~HarmonicMean.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/number/HarmonicMean.js~HarmonicMean#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/harmonicmean.js~harmonicmean#handleget&quot;,
    &quot;class/src/collectors/number/HarmonicMean.js~HarmonicMean.html#instance-method-handleGet&quot;,
    &quot;src/collectors/number/HarmonicMean.js~HarmonicMean#handleGet&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/max.js&quot;,
    &quot;file/src/collectors/number/Max.js.html&quot;,
    &quot;src/collectors/number/Max.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/number/max.js~max#constructor&quot;,
    &quot;class/src/collectors/number/Max.js~Max.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/number/Max.js~Max#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/max.js~max#handleprocess&quot;,
    &quot;class/src/collectors/number/Max.js~Max.html#instance-method-handleProcess&quot;,
    &quot;src/collectors/number/Max.js~Max#handleProcess&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/mean.js&quot;,
    &quot;file/src/collectors/number/Mean.js.html&quot;,
    &quot;src/collectors/number/Mean.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/number/mean.js~mean#constructor&quot;,
    &quot;class/src/collectors/number/Mean.js~Mean.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/number/Mean.js~Mean#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/mean.js~mean#handleget&quot;,
    &quot;class/src/collectors/number/Mean.js~Mean.html#instance-method-handleGet&quot;,
    &quot;src/collectors/number/Mean.js~Mean#handleGet&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/median.js&quot;,
    &quot;file/src/collectors/number/Median.js.html&quot;,
    &quot;src/collectors/number/Median.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/number/median.js~median#constructor&quot;,
    &quot;class/src/collectors/number/Median.js~Median.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/number/Median.js~Median#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/median.js~median#handleget&quot;,
    &quot;class/src/collectors/number/Median.js~Median.html#instance-method-handleGet&quot;,
    &quot;src/collectors/number/Median.js~Median#handleGet&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/midrange.js&quot;,
    &quot;file/src/collectors/number/MidRange.js.html&quot;,
    &quot;src/collectors/number/MidRange.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/number/midrange.js~midrange#constructor&quot;,
    &quot;class/src/collectors/number/MidRange.js~MidRange.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/number/MidRange.js~MidRange#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/midrange.js~midrange#handleget&quot;,
    &quot;class/src/collectors/number/MidRange.js~MidRange.html#instance-method-handleGet&quot;,
    &quot;src/collectors/number/MidRange.js~MidRange#handleGet&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/min.js&quot;,
    &quot;file/src/collectors/number/Min.js.html&quot;,
    &quot;src/collectors/number/Min.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/number/min.js~min#constructor&quot;,
    &quot;class/src/collectors/number/Min.js~Min.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/number/Min.js~Min#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/min.js~min#handleprocess&quot;,
    &quot;class/src/collectors/number/Min.js~Min.html#instance-method-handleProcess&quot;,
    &quot;src/collectors/number/Min.js~Min#handleProcess&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/powersumavgrunning.js&quot;,
    &quot;file/src/collectors/number/PowerSumAvgRunning.js.html&quot;,
    &quot;src/collectors/number/PowerSumAvgRunning.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/number/powersumavgrunning.js~powersumavgrunning#constructor&quot;,
    &quot;class/src/collectors/number/PowerSumAvgRunning.js~PowerSumAvgRunning.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/number/PowerSumAvgRunning.js~PowerSumAvgRunning#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/powersumavgrunning.js~powersumavgrunning#handleprocess&quot;,
    &quot;class/src/collectors/number/PowerSumAvgRunning.js~PowerSumAvgRunning.html#instance-method-handleProcess&quot;,
    &quot;src/collectors/number/PowerSumAvgRunning.js~PowerSumAvgRunning#handleProcess&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/product.js&quot;,
    &quot;file/src/collectors/number/Product.js.html&quot;,
    &quot;src/collectors/number/Product.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/number/product.js~product#constructor&quot;,
    &quot;class/src/collectors/number/Product.js~Product.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/number/Product.js~Product#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/product.js~product#handleprocess&quot;,
    &quot;class/src/collectors/number/Product.js~Product.html#instance-method-handleProcess&quot;,
    &quot;src/collectors/number/Product.js~Product#handleProcess&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/range.js&quot;,
    &quot;file/src/collectors/number/Range.js.html&quot;,
    &quot;src/collectors/number/Range.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/number/range.js~range#constructor&quot;,
    &quot;class/src/collectors/number/Range.js~Range.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/number/Range.js~Range#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/range.js~range#handleget&quot;,
    &quot;class/src/collectors/number/Range.js~Range.html#instance-method-handleGet&quot;,
    &quot;src/collectors/number/Range.js~Range#handleGet&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/standarddeviationrunning.js&quot;,
    &quot;file/src/collectors/number/StandardDeviationRunning.js.html&quot;,
    &quot;src/collectors/number/StandardDeviationRunning.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/number/standarddeviationrunning.js~standarddeviationrunning#constructor&quot;,
    &quot;class/src/collectors/number/StandardDeviationRunning.js~StandardDeviationRunning.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/number/StandardDeviationRunning.js~StandardDeviationRunning#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/standarddeviationrunning.js~standarddeviationrunning#handleget&quot;,
    &quot;class/src/collectors/number/StandardDeviationRunning.js~StandardDeviationRunning.html#instance-method-handleGet&quot;,
    &quot;src/collectors/number/StandardDeviationRunning.js~StandardDeviationRunning#handleGet&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/standarddeviationstable.js&quot;,
    &quot;file/src/collectors/number/StandardDeviationStable.js.html&quot;,
    &quot;src/collectors/number/StandardDeviationStable.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/number/standarddeviationstable.js~standarddeviationstable#constructor&quot;,
    &quot;class/src/collectors/number/StandardDeviationStable.js~StandardDeviationStable.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/number/StandardDeviationStable.js~StandardDeviationStable#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/standarddeviationstable.js~standarddeviationstable#handleget&quot;,
    &quot;class/src/collectors/number/StandardDeviationStable.js~StandardDeviationStable.html#instance-method-handleGet&quot;,
    &quot;src/collectors/number/StandardDeviationStable.js~StandardDeviationStable#handleGet&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/sum.js&quot;,
    &quot;file/src/collectors/number/Sum.js.html&quot;,
    &quot;src/collectors/number/Sum.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/number/sum.js~sum#constructor&quot;,
    &quot;class/src/collectors/number/Sum.js~Sum.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/number/Sum.js~Sum#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/sum.js~sum#handleprocess&quot;,
    &quot;class/src/collectors/number/Sum.js~Sum.html#instance-method-handleProcess&quot;,
    &quot;src/collectors/number/Sum.js~Sum#handleProcess&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/sumofrecipricals.js&quot;,
    &quot;file/src/collectors/number/SumOfRecipricals.js.html&quot;,
    &quot;src/collectors/number/SumOfRecipricals.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/number/sumofrecipricals.js~sumofrecipricals#constructor&quot;,
    &quot;class/src/collectors/number/SumOfRecipricals.js~SumOfRecipricals.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/number/SumOfRecipricals.js~SumOfRecipricals#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/sumofrecipricals.js~sumofrecipricals#handleprocess&quot;,
    &quot;class/src/collectors/number/SumOfRecipricals.js~SumOfRecipricals.html#instance-method-handleProcess&quot;,
    &quot;src/collectors/number/SumOfRecipricals.js~SumOfRecipricals#handleProcess&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/sumofsquareddeviationsstable.js&quot;,
    &quot;file/src/collectors/number/SumOfSquaredDeviationsStable.js.html&quot;,
    &quot;src/collectors/number/SumOfSquaredDeviationsStable.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/number/sumofsquareddeviationsstable.js~sumofsquareddeviationsstable#constructor&quot;,
    &quot;class/src/collectors/number/SumOfSquaredDeviationsStable.js~SumOfSquaredDeviationsStable.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/number/SumOfSquaredDeviationsStable.js~SumOfSquaredDeviationsStable#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/sumofsquareddeviationsstable.js~sumofsquareddeviationsstable#handleget&quot;,
    &quot;class/src/collectors/number/SumOfSquaredDeviationsStable.js~SumOfSquaredDeviationsStable.html#instance-method-handleGet&quot;,
    &quot;src/collectors/number/SumOfSquaredDeviationsStable.js~SumOfSquaredDeviationsStable#handleGet&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/values.js&quot;,
    &quot;file/src/collectors/number/Values.js.html&quot;,
    &quot;src/collectors/number/Values.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/number/values.js~values#constructor&quot;,
    &quot;class/src/collectors/number/Values.js~Values.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/number/Values.js~Values#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/values.js~values#handleprocess&quot;,
    &quot;class/src/collectors/number/Values.js~Values.html#instance-method-handleProcess&quot;,
    &quot;src/collectors/number/Values.js~Values#handleProcess&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/valuessorted.js&quot;,
    &quot;file/src/collectors/number/ValuesSorted.js.html&quot;,
    &quot;src/collectors/number/ValuesSorted.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/number/valuessorted.js~valuessorted#constructor&quot;,
    &quot;class/src/collectors/number/ValuesSorted.js~ValuesSorted.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/number/ValuesSorted.js~ValuesSorted#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/valuessorted.js~valuessorted#handleget&quot;,
    &quot;class/src/collectors/number/ValuesSorted.js~ValuesSorted.html#instance-method-handleGet&quot;,
    &quot;src/collectors/number/ValuesSorted.js~ValuesSorted#handleGet&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/variancerunning.js&quot;,
    &quot;file/src/collectors/number/VarianceRunning.js.html&quot;,
    &quot;src/collectors/number/VarianceRunning.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/number/variancerunning.js~variancerunning#constructor&quot;,
    &quot;class/src/collectors/number/VarianceRunning.js~VarianceRunning.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/number/VarianceRunning.js~VarianceRunning#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/variancerunning.js~variancerunning#handleget&quot;,
    &quot;class/src/collectors/number/VarianceRunning.js~VarianceRunning.html#instance-method-handleGet&quot;,
    &quot;src/collectors/number/VarianceRunning.js~VarianceRunning#handleGet&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/variancestable.js&quot;,
    &quot;file/src/collectors/number/VarianceStable.js.html&quot;,
    &quot;src/collectors/number/VarianceStable.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/number/variancestable.js~variancestable#constructor&quot;,
    &quot;class/src/collectors/number/VarianceStable.js~VarianceStable.html#instance-constructor-constructor&quot;,
    &quot;src/collectors/number/VarianceStable.js~VarianceStable#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/number/variancestable.js~variancestable#handleget&quot;,
    &quot;class/src/collectors/number/VarianceStable.js~VarianceStable.html#instance-method-handleGet&quot;,
    &quot;src/collectors/number/VarianceStable.js~VarianceStable#handleGet&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/filters/number/even.js&quot;,
    &quot;file/src/filters/number/even.js.html&quot;,
    &quot;src/filters/number/even.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/filters/number/float.js&quot;,
    &quot;file/src/filters/number/float.js.html&quot;,
    &quot;src/filters/number/float.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/filters/number/integer.js&quot;,
    &quot;file/src/filters/number/integer.js.html&quot;,
    &quot;src/filters/number/integer.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/filters/number/negative.js&quot;,
    &quot;file/src/filters/number/negative.js.html&quot;,
    &quot;src/filters/number/negative.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/filters/number/nonzero.js&quot;,
    &quot;file/src/filters/number/nonZero.js.html&quot;,
    &quot;src/filters/number/nonZero.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/filters/number/odd.js&quot;,
    &quot;file/src/filters/number/odd.js.html&quot;,
    &quot;src/filters/number/odd.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/filters/number/positive.js&quot;,
    &quot;file/src/filters/number/positive.js.html&quot;,
    &quot;src/filters/number/positive.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/filters/number/prime.js&quot;,
    &quot;file/src/filters/number/prime.js.html&quot;,
    &quot;src/filters/number/prime.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/filters/number/zero.js&quot;,
    &quot;file/src/filters/number/zero.js.html&quot;,
    &quot;src/filters/number/zero.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/helpers/collectors.js&quot;,
    &quot;file/src/helpers/collectors.js.html&quot;,
    &quot;src/helpers/collectors.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/helpers/collectors.number.js&quot;,
    &quot;file/src/helpers/collectors.number.js.html&quot;,
    &quot;src/helpers/collectors.number.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/helpers/filters.js&quot;,
    &quot;file/src/helpers/filters.js.html&quot;,
    &quot;src/helpers/filters.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/helpers/filters.number.js&quot;,
    &quot;file/src/helpers/filters.number.js.html&quot;,
    &quot;src/helpers/filters.number.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/helpers/leastfactor.js&quot;,
    &quot;file/src/helpers/leastFactor.js.html&quot;,
    &quot;src/helpers/leastFactor.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/index.js&quot;,
    &quot;file/src/index.js.html&quot;,
    &quot;src/index.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/stats/basestats.js&quot;,
    &quot;file/src/stats/BaseStats.js.html&quot;,
    &quot;src/stats/BaseStats.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/stats/basestats.js~basestats#addcollector&quot;,
    &quot;class/src/stats/BaseStats.js~BaseStats.html#instance-method-addCollector&quot;,
    &quot;src/stats/BaseStats.js~BaseStats#addCollector&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/stats/basestats.js~basestats#addfilter&quot;,
    &quot;class/src/stats/BaseStats.js~BaseStats.html#instance-method-addFilter&quot;,
    &quot;src/stats/BaseStats.js~BaseStats#addFilter&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/stats/basestats.js~basestats#addignore&quot;,
    &quot;class/src/stats/BaseStats.js~BaseStats.html#instance-method-addIgnore&quot;,
    &quot;src/stats/BaseStats.js~BaseStats#addIgnore&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/stats/basestats.js~basestats#constructor&quot;,
    &quot;class/src/stats/BaseStats.js~BaseStats.html#instance-constructor-constructor&quot;,
    &quot;src/stats/BaseStats.js~BaseStats#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/stats/basestats.js~basestats#get&quot;,
    &quot;class/src/stats/BaseStats.js~BaseStats.html#instance-method-get&quot;,
    &quot;src/stats/BaseStats.js~BaseStats#get&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/stats/basestats.js~basestats#process&quot;,
    &quot;class/src/stats/BaseStats.js~BaseStats.html#instance-method-process&quot;,
    &quot;src/stats/BaseStats.js~BaseStats#process&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/stats/basestats.js~basestats#processall&quot;,
    &quot;class/src/stats/BaseStats.js~BaseStats.html#instance-method-processAll&quot;,
    &quot;src/stats/BaseStats.js~BaseStats#processAll&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/stats/basestats.js~basestats#reset&quot;,
    &quot;class/src/stats/BaseStats.js~BaseStats.html#instance-method-reset&quot;,
    &quot;src/stats/BaseStats.js~BaseStats#reset&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/stats/number/advancednumberstats.js&quot;,
    &quot;file/src/stats/number/AdvancedNumberStats.js.html&quot;,
    &quot;src/stats/number/AdvancedNumberStats.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/stats/number/advancednumberstats.js~advancednumberstats#constructor&quot;,
    &quot;class/src/stats/number/AdvancedNumberStats.js~AdvancedNumberStats.html#instance-constructor-constructor&quot;,
    &quot;src/stats/number/AdvancedNumberStats.js~AdvancedNumberStats#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/stats/number/basicnumberstats.js&quot;,
    &quot;file/src/stats/number/BasicNumberStats.js.html&quot;,
    &quot;src/stats/number/BasicNumberStats.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/stats/number/basicnumberstats.js~basicnumberstats#constructor&quot;,
    &quot;class/src/stats/number/BasicNumberStats.js~BasicNumberStats.html#instance-constructor-constructor&quot;,
    &quot;src/stats/number/BasicNumberStats.js~BasicNumberStats#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/stats/number/numberstats.js&quot;,
    &quot;file/src/stats/number/NumberStats.js.html&quot;,
    &quot;src/stats/number/NumberStats.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/stats/number/numberstats.js~numberstats#constructor&quot;,
    &quot;class/src/stats/number/NumberStats.js~NumberStats.html#instance-constructor-constructor&quot;,
    &quot;src/stats/number/NumberStats.js~NumberStats#constructor&quot;,
    &quot;method&quot;
  ]
]