window.esdocSearchIndex = [
  [
    &quot;stats-collector/lib/advancedstatscollector~advancedstatscollector&quot;,
    &quot;class/src/AdvancedStatsCollector.js~AdvancedStatsCollector.html&quot;,
    &quot;<span>AdvancedStatsCollector</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/AdvancedStatsCollector</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/basestatscollector~basestatscollector&quot;,
    &quot;class/src/BaseStatsCollector.js~BaseStatsCollector.html&quot;,
    &quot;<span>BaseStatsCollector</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/BaseStatsCollector</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/basicstatscollector~basicstatscollector&quot;,
    &quot;class/src/BasicStatsCollector.js~BasicStatsCollector.html&quot;,
    &quot;<span>BasicStatsCollector</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/BasicStatsCollector</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/statscollector~statscollector&quot;,
    &quot;class/src/StatsCollector.js~StatsCollector.html&quot;,
    &quot;<span>StatsCollector</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/StatsCollector</span>&quot;,
    &quot;class&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/count~count&quot;,
    &quot;function/index.html#static-function-count&quot;,
    &quot;<span>count</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/count</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/filters/even~even&quot;,
    &quot;function/index.html#static-function-even&quot;,
    &quot;<span>even</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/filters/even</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/helpers/execmethod~execmethod&quot;,
    &quot;function/index.html#static-function-execMethod&quot;,
    &quot;<span>execMethod</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/helpers/execMethod</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/filteredcount~filteredcount&quot;,
    &quot;function/index.html#static-function-filteredCount&quot;,
    &quot;<span>filteredCount</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/filteredCount</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/filters/float~float&quot;,
    &quot;function/index.html#static-function-float&quot;,
    &quot;<span>float</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/filters/float</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/filters/integer~integer&quot;,
    &quot;function/index.html#static-function-integer&quot;,
    &quot;<span>integer</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/filters/integer</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/helpers/leastfactor~leastfactor&quot;,
    &quot;function/index.html#static-function-leastFactor&quot;,
    &quot;<span>leastFactor</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/helpers/leastFactor</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/max~max&quot;,
    &quot;function/index.html#static-function-max&quot;,
    &quot;<span>max</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/max</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/mean~mean&quot;,
    &quot;function/index.html#static-function-mean&quot;,
    &quot;<span>mean</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/mean</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/min~min&quot;,
    &quot;function/index.html#static-function-min&quot;,
    &quot;<span>min</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/min</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/filters/negative~negative&quot;,
    &quot;function/index.html#static-function-negative&quot;,
    &quot;<span>negative</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/filters/negative</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/filters/nonzero~nonzero&quot;,
    &quot;function/index.html#static-function-nonZero&quot;,
    &quot;<span>nonZero</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/filters/nonZero</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/filters/odd~odd&quot;,
    &quot;function/index.html#static-function-odd&quot;,
    &quot;<span>odd</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/filters/odd</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/filters/positive~positive&quot;,
    &quot;function/index.html#static-function-positive&quot;,
    &quot;<span>positive</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/filters/positive</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/powersumavg_running~powersumavg_running&quot;,
    &quot;function/index.html#static-function-powerSumAvg_running&quot;,
    &quot;<span>powerSumAvg_running</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/powerSumAvg_running</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/filters/prime~prime&quot;,
    &quot;function/index.html#static-function-prime&quot;,
    &quot;<span>prime</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/filters/prime</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/standarddeviation_running~standarddeviation_running&quot;,
    &quot;function/index.html#static-function-standardDeviation_running&quot;,
    &quot;<span>standardDeviation_running</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/standardDeviation_running</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/standarddeviation_stable~standarddeviation_stable&quot;,
    &quot;function/index.html#static-function-standardDeviation_stable&quot;,
    &quot;<span>standardDeviation_stable</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/standardDeviation_stable</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/sum~sum&quot;,
    &quot;function/index.html#static-function-sum&quot;,
    &quot;<span>sum</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/sum</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/sumofsquareddeviations_stable~sumofsquareddeviations_stable&quot;,
    &quot;function/index.html#static-function-sumOfSquaredDeviations_stable&quot;,
    &quot;<span>sumOfSquaredDeviations_stable</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/sumOfSquaredDeviations_stable</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/values~values&quot;,
    &quot;function/index.html#static-function-values&quot;,
    &quot;<span>values</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/values</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/variance_running~variance_running&quot;,
    &quot;function/index.html#static-function-variance_running&quot;,
    &quot;<span>variance_running</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/variance_running</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/collectors/variance_stable~variance_stable&quot;,
    &quot;function/index.html#static-function-variance_stable&quot;,
    &quot;<span>variance_stable</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/collectors/variance_stable</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;stats-collector/lib/filters/zero~zero&quot;,
    &quot;function/index.html#static-function-zero&quot;,
    &quot;<span>zero</span> <span class="\&quot;search-result-import-path\&quot;">stats-collector/lib/filters/zero</span>&quot;,
    &quot;function&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~array&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Array&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~arraybuffer&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~boolean&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Boolean&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~dataview&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~DataView&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~date&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Date&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~error&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Error&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~evalerror&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~EvalError&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~float32array&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Float32Array&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~float64array&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Float64Array&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~function&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Function&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~generator&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Generator&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~generatorfunction&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~infinity&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Infinity&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~int16array&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Int16Array&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~int32array&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Int32Array&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~int8array&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Int8Array&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~internalerror&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~InternalError&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~json&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~JSON&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~map&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Map&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~nan&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~NaN&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~number&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Number&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~object&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Object&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~promise&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Promise&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~proxy&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Proxy&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~rangeerror&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~RangeError&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~referenceerror&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~ReferenceError&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~reflect&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Reflect&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~regexp&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~RegExp&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~set&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Set&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~string&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~String&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~symbol&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Symbol&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~syntaxerror&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~SyntaxError&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~typeerror&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~TypeError&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~urierror&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~URIError&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~uint16array&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Uint16Array&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~uint32array&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Uint32Array&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~uint8array&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Uint8Array&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~uint8clampedarray&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~weakmap&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~WeakMap&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~weakset&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~WeakSet&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~boolean&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~boolean&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~function&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~function&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~null&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~null&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~number&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~number&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~object&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~object&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~string&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~string&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/ecmascriptexternal.js~undefined&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/ECMAScriptExternal.js~undefined&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/webapiexternal.js~audiocontext&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/WebAPIExternal.js~AudioContext&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/webapiexternal.js~canvasrenderingcontext2d&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/webapiexternal.js~documentfragment&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/WebAPIExternal.js~DocumentFragment&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/webapiexternal.js~element&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/WebAPIExternal.js~Element&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/webapiexternal.js~event&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/WebAPIExternal.js~Event&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/webapiexternal.js~node&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/WebAPIExternal.js~Node&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/webapiexternal.js~nodelist&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/WebAPIExternal.js~NodeList&quot;,
    &quot;external&quot;
  ],
  [
    &quot;builtinexternal/webapiexternal.js~xmlhttprequest&quot;,
    &quot;external/index.html&quot;,
    &quot;BuiltinExternal/WebAPIExternal.js~XMLHttpRequest&quot;,
    &quot;external&quot;
  ],
  [
    &quot;src/advancedstatscollector.js&quot;,
    &quot;file/src/AdvancedStatsCollector.js.html&quot;,
    &quot;src/AdvancedStatsCollector.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/advancedstatscollector.js~advancedstatscollector#constructor&quot;,
    &quot;class/src/AdvancedStatsCollector.js~AdvancedStatsCollector.html#instance-constructor-constructor&quot;,
    &quot;src/AdvancedStatsCollector.js~AdvancedStatsCollector#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/basestatscollector.js&quot;,
    &quot;file/src/BaseStatsCollector.js.html&quot;,
    &quot;src/BaseStatsCollector.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/basestatscollector.js~basestatscollector#addcollector&quot;,
    &quot;class/src/BaseStatsCollector.js~BaseStatsCollector.html#instance-method-addCollector&quot;,
    &quot;src/BaseStatsCollector.js~BaseStatsCollector#addCollector&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/basestatscollector.js~basestatscollector#addignore&quot;,
    &quot;class/src/BaseStatsCollector.js~BaseStatsCollector.html#instance-method-addIgnore&quot;,
    &quot;src/BaseStatsCollector.js~BaseStatsCollector#addIgnore&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/basestatscollector.js~basestatscollector#constructor&quot;,
    &quot;class/src/BaseStatsCollector.js~BaseStatsCollector.html#instance-constructor-constructor&quot;,
    &quot;src/BaseStatsCollector.js~BaseStatsCollector#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/basestatscollector.js~basestatscollector#get&quot;,
    &quot;class/src/BaseStatsCollector.js~BaseStatsCollector.html#instance-method-get&quot;,
    &quot;src/BaseStatsCollector.js~BaseStatsCollector#get&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/basestatscollector.js~basestatscollector#reset&quot;,
    &quot;class/src/BaseStatsCollector.js~BaseStatsCollector.html#instance-method-reset&quot;,
    &quot;src/BaseStatsCollector.js~BaseStatsCollector#reset&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/basestatscollector.js~basestatscollector#update&quot;,
    &quot;class/src/BaseStatsCollector.js~BaseStatsCollector.html#instance-method-update&quot;,
    &quot;src/BaseStatsCollector.js~BaseStatsCollector#update&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/basicstatscollector.js&quot;,
    &quot;file/src/BasicStatsCollector.js.html&quot;,
    &quot;src/BasicStatsCollector.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/basicstatscollector.js~basicstatscollector#constructor&quot;,
    &quot;class/src/BasicStatsCollector.js~BasicStatsCollector.html#instance-constructor-constructor&quot;,
    &quot;src/BasicStatsCollector.js~BasicStatsCollector#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/statscollector.js&quot;,
    &quot;file/src/StatsCollector.js.html&quot;,
    &quot;src/StatsCollector.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/statscollector.js~statscollector#constructor&quot;,
    &quot;class/src/StatsCollector.js~StatsCollector.html#instance-constructor-constructor&quot;,
    &quot;src/StatsCollector.js~StatsCollector#constructor&quot;,
    &quot;method&quot;
  ],
  [
    &quot;src/collectors/count.js&quot;,
    &quot;file/src/collectors/count.js.html&quot;,
    &quot;src/collectors/count.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/filteredcount.js&quot;,
    &quot;file/src/collectors/filteredCount.js.html&quot;,
    &quot;src/collectors/filteredCount.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/max.js&quot;,
    &quot;file/src/collectors/max.js.html&quot;,
    &quot;src/collectors/max.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/mean.js&quot;,
    &quot;file/src/collectors/mean.js.html&quot;,
    &quot;src/collectors/mean.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/min.js&quot;,
    &quot;file/src/collectors/min.js.html&quot;,
    &quot;src/collectors/min.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/powersumavg_running.js&quot;,
    &quot;file/src/collectors/powerSumAvg_running.js.html&quot;,
    &quot;src/collectors/powerSumAvg_running.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/standarddeviation_running.js&quot;,
    &quot;file/src/collectors/standardDeviation_running.js.html&quot;,
    &quot;src/collectors/standardDeviation_running.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/standarddeviation_stable.js&quot;,
    &quot;file/src/collectors/standardDeviation_stable.js.html&quot;,
    &quot;src/collectors/standardDeviation_stable.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/sum.js&quot;,
    &quot;file/src/collectors/sum.js.html&quot;,
    &quot;src/collectors/sum.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/sumofsquareddeviations_stable.js&quot;,
    &quot;file/src/collectors/sumOfSquaredDeviations_stable.js.html&quot;,
    &quot;src/collectors/sumOfSquaredDeviations_stable.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/values.js&quot;,
    &quot;file/src/collectors/values.js.html&quot;,
    &quot;src/collectors/values.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/variance_running.js&quot;,
    &quot;file/src/collectors/variance_running.js.html&quot;,
    &quot;src/collectors/variance_running.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/collectors/variance_stable.js&quot;,
    &quot;file/src/collectors/variance_stable.js.html&quot;,
    &quot;src/collectors/variance_stable.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/filters/even.js&quot;,
    &quot;file/src/filters/even.js.html&quot;,
    &quot;src/filters/even.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/filters/float.js&quot;,
    &quot;file/src/filters/float.js.html&quot;,
    &quot;src/filters/float.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/filters/integer.js&quot;,
    &quot;file/src/filters/integer.js.html&quot;,
    &quot;src/filters/integer.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/filters/negative.js&quot;,
    &quot;file/src/filters/negative.js.html&quot;,
    &quot;src/filters/negative.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/filters/nonzero.js&quot;,
    &quot;file/src/filters/nonZero.js.html&quot;,
    &quot;src/filters/nonZero.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/filters/odd.js&quot;,
    &quot;file/src/filters/odd.js.html&quot;,
    &quot;src/filters/odd.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/filters/positive.js&quot;,
    &quot;file/src/filters/positive.js.html&quot;,
    &quot;src/filters/positive.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/filters/prime.js&quot;,
    &quot;file/src/filters/prime.js.html&quot;,
    &quot;src/filters/prime.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/filters/zero.js&quot;,
    &quot;file/src/filters/zero.js.html&quot;,
    &quot;src/filters/zero.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/helpers/collectors.js&quot;,
    &quot;file/src/helpers/collectors.js.html&quot;,
    &quot;src/helpers/collectors.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/helpers/execmethod.js&quot;,
    &quot;file/src/helpers/execMethod.js.html&quot;,
    &quot;src/helpers/execMethod.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/helpers/filters.js&quot;,
    &quot;file/src/helpers/filters.js.html&quot;,
    &quot;src/helpers/filters.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/helpers/leastfactor.js&quot;,
    &quot;file/src/helpers/leastFactor.js.html&quot;,
    &quot;src/helpers/leastFactor.js&quot;,
    &quot;file&quot;
  ],
  [
    &quot;src/index.js&quot;,
    &quot;file/src/index.js.html&quot;,
    &quot;src/index.js&quot;,
    &quot;file&quot;
  ]
]