window.esdocSearchIndex = [
  [
    "stats-collector/lib/advancedstatscollector~advancedstatscollector",
    "class/src/AdvancedStatsCollector.js~AdvancedStatsCollector.html",
    "<span>AdvancedStatsCollector</span> <span class=\"search-result-import-path\">stats-collector/lib/AdvancedStatsCollector</span>",
    "class"
  ],
  [
    "stats-collector/lib/basestatscollector~basestatscollector",
    "class/src/BaseStatsCollector.js~BaseStatsCollector.html",
    "<span>BaseStatsCollector</span> <span class=\"search-result-import-path\">stats-collector/lib/BaseStatsCollector</span>",
    "class"
  ],
  [
    "stats-collector/lib/basicstatscollector~basicstatscollector",
    "class/src/BasicStatsCollector.js~BasicStatsCollector.html",
    "<span>BasicStatsCollector</span> <span class=\"search-result-import-path\">stats-collector/lib/BasicStatsCollector</span>",
    "class"
  ],
  [
    "stats-collector/lib/statscollector~statscollector",
    "class/src/StatsCollector.js~StatsCollector.html",
    "<span>StatsCollector</span> <span class=\"search-result-import-path\">stats-collector/lib/StatsCollector</span>",
    "class"
  ],
  [
    "stats-collector/lib/collectors/count~count",
    "function/index.html#static-function-count",
    "<span>count</span> <span class=\"search-result-import-path\">stats-collector/lib/collectors/count</span>",
    "function"
  ],
  [
    "stats-collector/lib/filters/even~even",
    "function/index.html#static-function-even",
    "<span>even</span> <span class=\"search-result-import-path\">stats-collector/lib/filters/even</span>",
    "function"
  ],
  [
    "stats-collector/lib/helpers/execmethod~execmethod",
    "function/index.html#static-function-execMethod",
    "<span>execMethod</span> <span class=\"search-result-import-path\">stats-collector/lib/helpers/execMethod</span>",
    "function"
  ],
  [
    "stats-collector/lib/collectors/filteredcount~filteredcount",
    "function/index.html#static-function-filteredCount",
    "<span>filteredCount</span> <span class=\"search-result-import-path\">stats-collector/lib/collectors/filteredCount</span>",
    "function"
  ],
  [
    "stats-collector/lib/filters/float~float",
    "function/index.html#static-function-float",
    "<span>float</span> <span class=\"search-result-import-path\">stats-collector/lib/filters/float</span>",
    "function"
  ],
  [
    "stats-collector/lib/filters/integer~integer",
    "function/index.html#static-function-integer",
    "<span>integer</span> <span class=\"search-result-import-path\">stats-collector/lib/filters/integer</span>",
    "function"
  ],
  [
    "stats-collector/lib/helpers/leastfactor~leastfactor",
    "function/index.html#static-function-leastFactor",
    "<span>leastFactor</span> <span class=\"search-result-import-path\">stats-collector/lib/helpers/leastFactor</span>",
    "function"
  ],
  [
    "stats-collector/lib/collectors/max~max",
    "function/index.html#static-function-max",
    "<span>max</span> <span class=\"search-result-import-path\">stats-collector/lib/collectors/max</span>",
    "function"
  ],
  [
    "stats-collector/lib/collectors/mean~mean",
    "function/index.html#static-function-mean",
    "<span>mean</span> <span class=\"search-result-import-path\">stats-collector/lib/collectors/mean</span>",
    "function"
  ],
  [
    "stats-collector/lib/collectors/min~min",
    "function/index.html#static-function-min",
    "<span>min</span> <span class=\"search-result-import-path\">stats-collector/lib/collectors/min</span>",
    "function"
  ],
  [
    "stats-collector/lib/filters/negative~negative",
    "function/index.html#static-function-negative",
    "<span>negative</span> <span class=\"search-result-import-path\">stats-collector/lib/filters/negative</span>",
    "function"
  ],
  [
    "stats-collector/lib/filters/nonzero~nonzero",
    "function/index.html#static-function-nonZero",
    "<span>nonZero</span> <span class=\"search-result-import-path\">stats-collector/lib/filters/nonZero</span>",
    "function"
  ],
  [
    "stats-collector/lib/filters/odd~odd",
    "function/index.html#static-function-odd",
    "<span>odd</span> <span class=\"search-result-import-path\">stats-collector/lib/filters/odd</span>",
    "function"
  ],
  [
    "stats-collector/lib/filters/positive~positive",
    "function/index.html#static-function-positive",
    "<span>positive</span> <span class=\"search-result-import-path\">stats-collector/lib/filters/positive</span>",
    "function"
  ],
  [
    "stats-collector/lib/collectors/powersumavg_running~powersumavg_running",
    "function/index.html#static-function-powerSumAvg_running",
    "<span>powerSumAvg_running</span> <span class=\"search-result-import-path\">stats-collector/lib/collectors/powerSumAvg_running</span>",
    "function"
  ],
  [
    "stats-collector/lib/filters/prime~prime",
    "function/index.html#static-function-prime",
    "<span>prime</span> <span class=\"search-result-import-path\">stats-collector/lib/filters/prime</span>",
    "function"
  ],
  [
    "stats-collector/lib/collectors/standarddeviation_running~standarddeviation_running",
    "function/index.html#static-function-standardDeviation_running",
    "<span>standardDeviation_running</span> <span class=\"search-result-import-path\">stats-collector/lib/collectors/standardDeviation_running</span>",
    "function"
  ],
  [
    "stats-collector/lib/collectors/standarddeviation_stable~standarddeviation_stable",
    "function/index.html#static-function-standardDeviation_stable",
    "<span>standardDeviation_stable</span> <span class=\"search-result-import-path\">stats-collector/lib/collectors/standardDeviation_stable</span>",
    "function"
  ],
  [
    "stats-collector/lib/collectors/sum~sum",
    "function/index.html#static-function-sum",
    "<span>sum</span> <span class=\"search-result-import-path\">stats-collector/lib/collectors/sum</span>",
    "function"
  ],
  [
    "stats-collector/lib/collectors/sumofsquareddeviations_stable~sumofsquareddeviations_stable",
    "function/index.html#static-function-sumOfSquaredDeviations_stable",
    "<span>sumOfSquaredDeviations_stable</span> <span class=\"search-result-import-path\">stats-collector/lib/collectors/sumOfSquaredDeviations_stable</span>",
    "function"
  ],
  [
    "stats-collector/lib/collectors/values~values",
    "function/index.html#static-function-values",
    "<span>values</span> <span class=\"search-result-import-path\">stats-collector/lib/collectors/values</span>",
    "function"
  ],
  [
    "stats-collector/lib/collectors/variance_running~variance_running",
    "function/index.html#static-function-variance_running",
    "<span>variance_running</span> <span class=\"search-result-import-path\">stats-collector/lib/collectors/variance_running</span>",
    "function"
  ],
  [
    "stats-collector/lib/collectors/variance_stable~variance_stable",
    "function/index.html#static-function-variance_stable",
    "<span>variance_stable</span> <span class=\"search-result-import-path\">stats-collector/lib/collectors/variance_stable</span>",
    "function"
  ],
  [
    "stats-collector/lib/filters/zero~zero",
    "function/index.html#static-function-zero",
    "<span>zero</span> <span class=\"search-result-import-path\">stats-collector/lib/filters/zero</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/advancedstatscollector.js",
    "file/src/AdvancedStatsCollector.js.html",
    "src/AdvancedStatsCollector.js",
    "file"
  ],
  [
    "src/advancedstatscollector.js~advancedstatscollector#constructor",
    "class/src/AdvancedStatsCollector.js~AdvancedStatsCollector.html#instance-constructor-constructor",
    "src/AdvancedStatsCollector.js~AdvancedStatsCollector#constructor",
    "method"
  ],
  [
    "src/basestatscollector.js",
    "file/src/BaseStatsCollector.js.html",
    "src/BaseStatsCollector.js",
    "file"
  ],
  [
    "src/basestatscollector.js~basestatscollector#addcollector",
    "class/src/BaseStatsCollector.js~BaseStatsCollector.html#instance-method-addCollector",
    "src/BaseStatsCollector.js~BaseStatsCollector#addCollector",
    "method"
  ],
  [
    "src/basestatscollector.js~basestatscollector#addignore",
    "class/src/BaseStatsCollector.js~BaseStatsCollector.html#instance-method-addIgnore",
    "src/BaseStatsCollector.js~BaseStatsCollector#addIgnore",
    "method"
  ],
  [
    "src/basestatscollector.js~basestatscollector#constructor",
    "class/src/BaseStatsCollector.js~BaseStatsCollector.html#instance-constructor-constructor",
    "src/BaseStatsCollector.js~BaseStatsCollector#constructor",
    "method"
  ],
  [
    "src/basestatscollector.js~basestatscollector#get",
    "class/src/BaseStatsCollector.js~BaseStatsCollector.html#instance-method-get",
    "src/BaseStatsCollector.js~BaseStatsCollector#get",
    "method"
  ],
  [
    "src/basestatscollector.js~basestatscollector#reset",
    "class/src/BaseStatsCollector.js~BaseStatsCollector.html#instance-method-reset",
    "src/BaseStatsCollector.js~BaseStatsCollector#reset",
    "method"
  ],
  [
    "src/basestatscollector.js~basestatscollector#update",
    "class/src/BaseStatsCollector.js~BaseStatsCollector.html#instance-method-update",
    "src/BaseStatsCollector.js~BaseStatsCollector#update",
    "method"
  ],
  [
    "src/basicstatscollector.js",
    "file/src/BasicStatsCollector.js.html",
    "src/BasicStatsCollector.js",
    "file"
  ],
  [
    "src/basicstatscollector.js~basicstatscollector#constructor",
    "class/src/BasicStatsCollector.js~BasicStatsCollector.html#instance-constructor-constructor",
    "src/BasicStatsCollector.js~BasicStatsCollector#constructor",
    "method"
  ],
  [
    "src/statscollector.js",
    "file/src/StatsCollector.js.html",
    "src/StatsCollector.js",
    "file"
  ],
  [
    "src/statscollector.js~statscollector#constructor",
    "class/src/StatsCollector.js~StatsCollector.html#instance-constructor-constructor",
    "src/StatsCollector.js~StatsCollector#constructor",
    "method"
  ],
  [
    "src/collectors/count.js",
    "file/src/collectors/count.js.html",
    "src/collectors/count.js",
    "file"
  ],
  [
    "src/collectors/filteredcount.js",
    "file/src/collectors/filteredCount.js.html",
    "src/collectors/filteredCount.js",
    "file"
  ],
  [
    "src/collectors/max.js",
    "file/src/collectors/max.js.html",
    "src/collectors/max.js",
    "file"
  ],
  [
    "src/collectors/mean.js",
    "file/src/collectors/mean.js.html",
    "src/collectors/mean.js",
    "file"
  ],
  [
    "src/collectors/min.js",
    "file/src/collectors/min.js.html",
    "src/collectors/min.js",
    "file"
  ],
  [
    "src/collectors/powersumavg_running.js",
    "file/src/collectors/powerSumAvg_running.js.html",
    "src/collectors/powerSumAvg_running.js",
    "file"
  ],
  [
    "src/collectors/standarddeviation_running.js",
    "file/src/collectors/standardDeviation_running.js.html",
    "src/collectors/standardDeviation_running.js",
    "file"
  ],
  [
    "src/collectors/standarddeviation_stable.js",
    "file/src/collectors/standardDeviation_stable.js.html",
    "src/collectors/standardDeviation_stable.js",
    "file"
  ],
  [
    "src/collectors/sum.js",
    "file/src/collectors/sum.js.html",
    "src/collectors/sum.js",
    "file"
  ],
  [
    "src/collectors/sumofsquareddeviations_stable.js",
    "file/src/collectors/sumOfSquaredDeviations_stable.js.html",
    "src/collectors/sumOfSquaredDeviations_stable.js",
    "file"
  ],
  [
    "src/collectors/values.js",
    "file/src/collectors/values.js.html",
    "src/collectors/values.js",
    "file"
  ],
  [
    "src/collectors/variance_running.js",
    "file/src/collectors/variance_running.js.html",
    "src/collectors/variance_running.js",
    "file"
  ],
  [
    "src/collectors/variance_stable.js",
    "file/src/collectors/variance_stable.js.html",
    "src/collectors/variance_stable.js",
    "file"
  ],
  [
    "src/filters/even.js",
    "file/src/filters/even.js.html",
    "src/filters/even.js",
    "file"
  ],
  [
    "src/filters/float.js",
    "file/src/filters/float.js.html",
    "src/filters/float.js",
    "file"
  ],
  [
    "src/filters/integer.js",
    "file/src/filters/integer.js.html",
    "src/filters/integer.js",
    "file"
  ],
  [
    "src/filters/negative.js",
    "file/src/filters/negative.js.html",
    "src/filters/negative.js",
    "file"
  ],
  [
    "src/filters/nonzero.js",
    "file/src/filters/nonZero.js.html",
    "src/filters/nonZero.js",
    "file"
  ],
  [
    "src/filters/odd.js",
    "file/src/filters/odd.js.html",
    "src/filters/odd.js",
    "file"
  ],
  [
    "src/filters/positive.js",
    "file/src/filters/positive.js.html",
    "src/filters/positive.js",
    "file"
  ],
  [
    "src/filters/prime.js",
    "file/src/filters/prime.js.html",
    "src/filters/prime.js",
    "file"
  ],
  [
    "src/filters/zero.js",
    "file/src/filters/zero.js.html",
    "src/filters/zero.js",
    "file"
  ],
  [
    "src/helpers/collectors.js",
    "file/src/helpers/collectors.js.html",
    "src/helpers/collectors.js",
    "file"
  ],
  [
    "src/helpers/execmethod.js",
    "file/src/helpers/execMethod.js.html",
    "src/helpers/execMethod.js",
    "file"
  ],
  [
    "src/helpers/filters.js",
    "file/src/helpers/filters.js.html",
    "src/helpers/filters.js",
    "file"
  ],
  [
    "src/helpers/leastfactor.js",
    "file/src/helpers/leastFactor.js.html",
    "src/helpers/leastFactor.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ]
]