'use strict';
const fs = require('fs');
const path = require('path');
const root = path.resolve(`${__dirname}/../`);

const build = function (srcDir, importPrefix, destFilename) {
  const names = [];
  let contents = '/* generated by scripts/build.helpers.js */\n/*eslint camelcase: 0 */';
  fs.readdirSync(srcDir).forEach(function (file) {
    const name = file.replace('.js', '');
    names.push(name);
    contents = `${contents}\nimport ${name} from '${importPrefix}${name}';`;
  });
  contents = `${contents}\nexport {\n  ${names.join(',\n  ')}\n};\n`;
  fs.writeFileSync(destFilename, contents, 'utf-8');
};

// collectors
build(
  `${root}/src/collectors/number`,
  '../collectors/number/',
  `${root}/src/helpers/collectors.number.js`
);

// filters
build(
  `${root}/src/filters/number`,
  '../filters/number/',
  `${root}/src/helpers/filters.number.js`
);
