'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.variance_stable = exports.variance_running = exports.sumOfSquaredDeviations_stable = exports.sum = exports.standardDeviation_stable = exports.standardDeviation_running = exports.powerSumAvg_running = exports.min = exports.mean = exports.max = exports.filteredCount = exports.count = exports._values = undefined;

var _values2 = require('../collectors/_values');

var _values3 = _interopRequireDefault(_values2);

var _count = require('../collectors/count');

var _count2 = _interopRequireDefault(_count);

var _filteredCount = require('../collectors/filteredCount');

var _filteredCount2 = _interopRequireDefault(_filteredCount);

var _max = require('../collectors/max');

var _max2 = _interopRequireDefault(_max);

var _mean = require('../collectors/mean');

var _mean2 = _interopRequireDefault(_mean);

var _min = require('../collectors/min');

var _min2 = _interopRequireDefault(_min);

var _powerSumAvg_running = require('../collectors/powerSumAvg_running');

var _powerSumAvg_running2 = _interopRequireDefault(_powerSumAvg_running);

var _standardDeviation_running = require('../collectors/standardDeviation_running');

var _standardDeviation_running2 = _interopRequireDefault(_standardDeviation_running);

var _standardDeviation_stable = require('../collectors/standardDeviation_stable');

var _standardDeviation_stable2 = _interopRequireDefault(_standardDeviation_stable);

var _sum = require('../collectors/sum');

var _sum2 = _interopRequireDefault(_sum);

var _sumOfSquaredDeviations_stable = require('../collectors/sumOfSquaredDeviations_stable');

var _sumOfSquaredDeviations_stable2 = _interopRequireDefault(_sumOfSquaredDeviations_stable);

var _variance_running = require('../collectors/variance_running');

var _variance_running2 = _interopRequireDefault(_variance_running);

var _variance_stable = require('../collectors/variance_stable');

var _variance_stable2 = _interopRequireDefault(_variance_stable);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

exports._values = _values3.default;
exports.count = _count2.default;
exports.filteredCount = _filteredCount2.default;
exports.max = _max2.default;
exports.mean = _mean2.default;
exports.min = _min2.default;
exports.powerSumAvg_running = _powerSumAvg_running2.default;
exports.standardDeviation_running = _standardDeviation_running2.default;
exports.standardDeviation_stable = _standardDeviation_stable2.default;
exports.sum = _sum2.default;
exports.sumOfSquaredDeviations_stable = _sumOfSquaredDeviations_stable2.default;
exports.variance_running = _variance_running2.default;
exports.variance_stable = _variance_stable2.default; /* generated by gulpfile.js */