'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.zero = exports.prime = exports.positive = exports.odd = exports.nonZero = exports.negative = exports.integer = exports.float = exports.even = undefined;

var _even = require('../filters/even');

var _even2 = _interopRequireDefault(_even);

var _float = require('../filters/float');

var _float2 = _interopRequireDefault(_float);

var _integer = require('../filters/integer');

var _integer2 = _interopRequireDefault(_integer);

var _negative = require('../filters/negative');

var _negative2 = _interopRequireDefault(_negative);

var _nonZero = require('../filters/nonZero');

var _nonZero2 = _interopRequireDefault(_nonZero);

var _odd = require('../filters/odd');

var _odd2 = _interopRequireDefault(_odd);

var _positive = require('../filters/positive');

var _positive2 = _interopRequireDefault(_positive);

var _prime = require('../filters/prime');

var _prime2 = _interopRequireDefault(_prime);

var _zero = require('../filters/zero');

var _zero2 = _interopRequireDefault(_zero);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

exports.even = _even2.default;
exports.float = _float2.default;
exports.integer = _integer2.default;
exports.negative = _negative2.default;
exports.nonZero = _nonZero2.default;
exports.odd = _odd2.default;
exports.positive = _positive2.default;
exports.prime = _prime2.default;
exports.zero = _zero2.default; /* generated by gulpfile.js */